### ISSUE TITLE
add hello world in any language possible

### ISSUE THREAD

**Issue by piyush97** [piyush97/HelloWorld#5]
Add a Hello World in any programming language you know

**Comment by piyush97** [comment]
# Don't forget to add yourself to the contributor's list

**Comment by piyush97** [comment]
# Be fast and contribute to Hacktoberfest!

**Comment by gcoria** [comment]
Added in Groovy #26

**Comment by yevseytsev** [comment]
I will add "hello world" program on Pascal

**Comment by piyush97** [comment]
You all are doing a great work
